## Replace tables with Dataflow tables
 

let
    Source = PowerPlatform.Dataflows(null),
    Workspaces = Source{[Id="Workspaces"]}[Data],
    #"wokrspaceid" = Workspaces{[workspaceId="c7e60087-de7d-47ee-9058-870561595b39"]}[Data],
    #"dataflowid" = #"wokrspaceid"{[dataflowId="80ac8046-1118-4c63-b159-0af633321a2f"]}[Data],
    dataflowtable = #"dataflowid"{[entity="dataflowtablename",version=""]}[Data]
in
    dataflowtable

##Filter by MAx value
let
    Source = #table(type table[Value = Int64.Type],List.Zip({{1..10}&{1..10}&{1..10}})),
    #"Filtered Rows" = Table.SelectRows(Source, each ([Value] = List.Max(Source[Value])))
in
    #"Filtered Rows"


##API Call with Client Secret & Client ID

	let
    Source = Json.Document(Web.Contents(""api_url"", [Headers=[client_secret=""xxxx"", client_id=""xxxx""]])),
    #""Converted to Table"" = Table.FromList(Source, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
   
in
   #""Converted to Table""
   
   //Expand to columns as next step in PowerQuery



##API Call with Access Token
let
    Source = Json.Document(Web.Contents("api_url", [Headers=[Authorization=get_token()]])),
    #"Converted to Table" = Table.FromList(Source, Splitter.SplitByNothing(), null, null, ExtraValues.Error)
in
    #"Converted to Table"
// expand table to retrieve fields


##Transform single column into multiple columns based on row num
Table.FromRows(List.Split(#"step"[Column],5))


##Clean way to bulk load  csv files 
Csv.Document([Content])

##Clean way to bulk load excel files
Excel.Workbook([Content])

##Filter by list
Table.SelectRows(#prevstep, each List.Contains(listname, [ColumnName]))

##Define datatype with custom Columns	add optional argument type after change type 
https://gorilla.bi/power-query/define-data-type-custom-column/
Data Type	Syntax 1	Syntax 2
Whole Number	Int64.Type	–
Decimal Number	Number.Type	type number
Dates	Date.Type	type date
Text	Text.Type	type text
Binary		type binary
Date/Time		type datetime
Date/Time/Timezone		type datetimezone
Duration		type duration
Function		type function
List		type list
True/False		type logical
Record		type record
Any		type any
Any Non-Null		type anynonnull
None		type none
Null		type null
Type		type type

##Load sharepoint excel file using web connector
Open the sharepoint excel on excel desktop app
Goto File->Info->Copy Path
Use web connector in PBI and paste the path copied from excel file
delete ‘?web=1’
authenticate with credentials



## Load Contents of Sharepoint

1. Connect using SharePoint List to any list within the correct site. (using Windows credentials)

2. In query editor manually change the source code


from this:
 
= SharePoint.Tables("https://isharenew.company.com/sites/example_site", [ApiVersion = 15])
 

to this :
 

= SharePoint.Contents("https://isharenew.company.com/sites/example_site", [ApiVersion = 14])


## promote headers within csv file 
= Table.AddColumn(#"Removed Other Columns", "Custom", each Table.PromoteHeaders(Csv.Document([Content])))


## Filter TopN values
= Table.SelectRows(#"Sorted Rows", each
    let list=List.Min(List.FirstN(List.Sort(List.Distinct(#"Sorted Rows"[Week Num]),Order.Descending),3))
    in
     [Week Num] >= list)


